### ISSUE TITLE
Where is the download link?

### ISSUE THREAD

**Issue by ghost** [BalestraPatrick/OpenIt#3]
I downloaded it once before.
I want to redownload it.

THX!

**Comment by BalestraPatrick** [comment]
If you have a developer account, you can download it from here and install it on your device.
If not, I'm working on an App Store version that will (hopefully) be available in the future to download for everyone.

**Comment by jwvim** [comment]
Hi, Friend.

It's been two month. Have you worked out the App Store Version?
